repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
      # - id: no-commit-to-branch
      #description: Main branch not allowed
      #args: ['--branch', 'main']
    - id: requirements-txt-fixer
    - id: trailing-whitespace
    - id: detect-private-key
    - id: check-shebang-scripts-are-executable
    - id: check-merge-conflict
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
    - id: black
      args: [--diff, --check]
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v3.0.0a3
  hooks:
    - id: pylint
      args: [--disable=all, --enable=unused-import]
