repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
      # - id: no-commit-to-branch
      #description: Main branch not allowed
      #args: ['--branch', 'main']
    - id: requirements-txt-fixer
    - id: trailing-whitespace
    - id: detect-private-key
    - id: check-shebang-scripts-are-executable
    - id: check-merge-conflict
